using SIMS.Domain.Enums;

namespace SIMS.Application.DTOs.SurplusLines;

public record SurplusLinesStateSetupDto(
    Guid Id,
    string StateCode,
    Guid? ProgramConfigurationId,
    string? ProgramName,
    Guid? CarrierId,
    string? CarrierName,
    PolicyLineOfBusiness? LineOfBusiness,
    string? LineOfBusinessLabel,
    Guid? ProgramCarrierLobStateId,
    DateOnly EffectiveDate,
    DateOnly? ExpirationDate,
    bool IsActive,
    bool FilingRequired,
    string LicenseHolderType,
    string FilingBrokerName,
    string LicenseNumber,
    string LicenseState,
    string BrokerAddressLine1,
    string? BrokerAddressLine2,
    string BrokerCity,
    string BrokerState,
    string BrokerZipCode,
    string BrokerCountry,
    string? StampingWording,
    string? RequiredNoticeText,
    string? PaperworkNotes,
    string? FilingNotes,
    long? SurplusLinesTaxFeeDefinitionId,
    string? SurplusLinesTaxFeeName,
    long? StampingFeeDefinitionId,
    string? StampingFeeName,
    long? FilingFeeDefinitionId,
    string? FilingFeeName,
    long? StatePayeeId,
    string? StatePayeeName,
    long? FilingPayeeId,
    string? FilingPayeeName,
    bool CreateFilingPayable,
    int? FilingPaymentTermsDays,
    string? FilingFrequency,
    int? FilingDueDayOfMonth,
    string? FilingMethod,
    string? FilingPortalUrl,
    string RequiredFilingFormsJson,
    bool DiligentSearchRequired,
    string? DiligentSearchNotes,
    bool AffidavitRequired,
    string? AffidavitNotes,
    IReadOnlyList<string> FeeValidationMessages,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    Guid? CompanyLicenseId,
    string? CompanyLicenseHolder,
    // F15: the payee that actually receives the SL tax payable is resolved from the linked
    // SL-tax fee (the fee engine is the payee SOT); shown read-only on the SL setup screen.
    string? ResolvedTaxPayeeName
);

public record UpsertSurplusLinesStateSetupRequest(
    string StateCode,
    Guid? ProgramConfigurationId,
    Guid? CarrierId,
    PolicyLineOfBusiness? LineOfBusiness,
    DateOnly EffectiveDate,
    DateOnly? ExpirationDate,
    bool IsActive,
    bool FilingRequired,
    string LicenseHolderType,
    string FilingBrokerName,
    string LicenseNumber,
    string LicenseState,
    string BrokerAddressLine1,
    string? BrokerAddressLine2,
    string BrokerCity,
    string BrokerState,
    string BrokerZipCode,
    string BrokerCountry,
    string? StampingWording,
    string? RequiredNoticeText,
    string? PaperworkNotes,
    string? FilingNotes,
    long? SurplusLinesTaxFeeDefinitionId,
    long? StampingFeeDefinitionId,
    long? FilingFeeDefinitionId,
    long? StatePayeeId = null,
    long? FilingPayeeId = null,
    bool CreateFilingPayable = false,
    int? FilingPaymentTermsDays = null,
    string? FilingFrequency = null,
    int? FilingDueDayOfMonth = null,
    string? FilingMethod = null,
    string? FilingPortalUrl = null,
    string RequiredFilingFormsJson = "[]",
    bool DiligentSearchRequired = false,
    string? DiligentSearchNotes = null,
    bool AffidavitRequired = false,
    string? AffidavitNotes = null,
    Guid? CompanyLicenseId = null
);

public record CopySurplusLinesStateSetupRequest(string TargetStateCode);
