using SIMS.Domain.Enums;

namespace SIMS.Application.DTOs.Intermediaries;

public record IntermediaryListItemDto(
    Guid Id,
    string Name,
    string? ReferenceNumber,
    string? Email,
    string? Phone,
    string? City,
    string? State,
    bool IsActive,
    int BrokerageSetupCount,
    int ActiveBrokerageSetupCount);

public record IntermediaryDto(
    Guid Id,
    string Name,
    string? ReferenceNumber,
    string? Email,
    string? Phone,
    string? AddressLine1,
    string? AddressLine2,
    string? City,
    string? State,
    string? ZipCode,
    string? Country,
    string? BankName,
    string? BankAccountName,
    string? BankAccountLast4,
    string? BankRoutingNumber,
    string? BankSwiftCode,
    string? BankInstructions,
    bool IsActive,
    string? Notes,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    IReadOnlyList<IntermediaryBrokerageSetupDto> BrokerageSetups);

public record IntermediaryBrokerageSetupDto(
    Guid Id,
    Guid IntermediaryId,
    Guid ProgramConfigurationId,
    string ProgramName,
    Guid CarrierId,
    string CarrierName,
    PolicyLineOfBusiness? LineOfBusiness,
    string LineOfBusinessLabel,
    Guid? ProgramCarrierId,
    Guid? ProgramCarrierLineOfBusinessId,
    DateOnly EffectiveDate,
    DateOnly? ExpirationDate,
    decimal? BrokerageRate,
    bool CreatePayable,
    long? PayablePayeeId,
    string? PayablePayeeName,
    bool IsActive,
    string? Notes);

public record CreateIntermediaryRequest(
    string Name,
    string? ReferenceNumber,
    string? Email,
    string? Phone,
    string? AddressLine1,
    string? AddressLine2,
    string? City,
    string? State,
    string? ZipCode,
    string? Country,
    string? BankName,
    string? BankAccountName,
    string? BankAccountLast4,
    string? BankRoutingNumber,
    string? BankSwiftCode,
    string? BankInstructions,
    bool IsActive,
    string? Notes);

public record UpdateIntermediaryRequest(
    string Name,
    string? ReferenceNumber,
    string? Email,
    string? Phone,
    string? AddressLine1,
    string? AddressLine2,
    string? City,
    string? State,
    string? ZipCode,
    string? Country,
    string? BankName,
    string? BankAccountName,
    string? BankAccountLast4,
    string? BankRoutingNumber,
    string? BankSwiftCode,
    string? BankInstructions,
    bool IsActive,
    string? Notes);

public record UpsertIntermediaryBrokerageSetupRequest(
    Guid ProgramConfigurationId,
    Guid CarrierId,
    PolicyLineOfBusiness? LineOfBusiness,
    DateOnly EffectiveDate,
    DateOnly? ExpirationDate,
    decimal? BrokerageRate,
    bool CreatePayable,
    long? PayablePayeeId,
    bool IsActive,
    string? Notes);
