// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIMS.Infrastructure.Data;

#nullable disable

namespace SIMS.Infrastructure.Migrations.SafetyAnalytics
{
    [DbContext(typeof(SafetyAnalyticsDbContext))]
    partial class SafetyAnalyticsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIMS.Domain.Entities.FmcsaAnalytics.FmcsaAnalyticsImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("RowsImported")
                        .HasColumnType("integer")
                        .HasColumnName("rows_imported");

                    b.Property<string>("SnapshotMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("snapshot_month");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_name");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotMonth", "SourceName");

                    b.ToTable("fmcsa_analytics_import_batches", (string)null);
                });

            modelBuilder.Entity("SIMS.Domain.Entities.FmcsaAnalytics.FmcsaBasicPeerMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Basic")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("basic");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Exposure")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("exposure");

                    b.Property<int>("InspectionWithViolationCount")
                        .HasColumnType("integer")
                        .HasColumnName("inspection_with_violation_count");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<decimal?>("OfficialMeasure")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("official_measure");

                    b.Property<int>("OutOfServiceCount")
                        .HasColumnType("integer")
                        .HasColumnName("out_of_service_count");

                    b.Property<string>("PeerGroupKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("peer_group_key");

                    b.Property<int?>("PeerPopulation")
                        .HasColumnType("integer")
                        .HasColumnName("peer_population");

                    b.Property<int?>("PeerRank")
                        .HasColumnType("integer")
                        .HasColumnName("peer_rank");

                    b.Property<decimal?>("SimsMeasure")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("sims_measure");

                    b.Property<decimal?>("SimsPercentile")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("sims_percentile");

                    b.Property<string>("SnapshotMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("snapshot_month");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsDotNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("us_dot_number");

                    b.Property<int>("ViolationCount")
                        .HasColumnType("integer")
                        .HasColumnName("violation_count");

                    b.Property<decimal>("WeightedViolationScore")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("weighted_violation_score");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotMonth", "UsDotNumber", "Basic")
                        .IsUnique();

                    b.HasIndex("SnapshotMonth", "Basic", "PeerGroupKey", "SimsMeasure");

                    b.ToTable("fmcsa_basic_peer_measures", (string)null);
                });

            modelBuilder.Entity("SIMS.Domain.Entities.FmcsaAnalytics.FmcsaCarrierPeerSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DriverCount")
                        .HasColumnType("integer")
                        .HasColumnName("driver_count");

                    b.Property<int>("DriverInspectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("driver_inspection_count");

                    b.Property<int>("DriverOosInspectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("driver_oos_inspection_count");

                    b.Property<int>("InspectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("inspection_count");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LegalName")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("legal_name");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<int?>("MileageYear")
                        .HasColumnType("integer")
                        .HasColumnName("mileage_year");

                    b.Property<int?>("PowerUnits")
                        .HasColumnType("integer")
                        .HasColumnName("power_units");

                    b.Property<string>("SnapshotMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("snapshot_month");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsDotNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("us_dot_number");

                    b.Property<int>("VehicleInspectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_inspection_count");

                    b.Property<int>("VehicleOosInspectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_oos_inspection_count");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotMonth", "PowerUnits");

                    b.HasIndex("SnapshotMonth", "UsDotNumber")
                        .IsUnique();

                    b.ToTable("fmcsa_carrier_peer_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
