<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Google.Cloud.DocumentAI.V1" Version="3.25.0" />
    <PackageReference Include="Microsoft.Graph" Version="5.79.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Linux" Version="8.3.1.2" />
    <PackageReference Include="PDFtoImage" Version="5.1.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="3.119.1" />
    <PackageReference Include="Syncfusion.DocIO.Net.Core" Version="33.1.46" />
    <PackageReference Include="Syncfusion.DocIORenderer.Net.Core" Version="33.1.46" />
    <PackageReference Include="Syncfusion.HtmlToPdfConverter.Net.Linux" Version="33.1.46" />
    <PackageReference Include="Syncfusion.Pdf.Net.Core" Version="33.1.46" />
    <PackageReference Include="QuestPDF" Version="2024.12.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SIMS.Application\SIMS.Application.csproj" />
    <ProjectReference Include="..\SIMS.Domain\SIMS.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Templates\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
